name: Build Windows Executable

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 先安装 PyQt5，避免依赖冲突
        pip install PyQt5==5.15.9
        pip install -r requirements.txt
        # 安装打包工具
        pip install pyinstaller==6.3.0
        # 验证安装
        python -c "import PyQt5; print('PyQt5 version:', PyQt5.__version__)"
        
    - name: Get version
      id: get_version
      run: |
        $version = if ($env:GITHUB_REF_TYPE -eq 'tag') {
          $env:GITHUB_REF_NAME
        } else {
          "dev-$env:GITHUB_SHA".Substring(0, 12)
        }
        echo "VERSION=$version" >> $env:GITHUB_ENV
      shell: pwsh
        
    - name: Build with PyInstaller
      run: |
        # 添加所有必要的依赖
        pyinstaller --noconfirm --onefile --windowed `
          --name "FileTransfer" `
          --version-file "version.txt" `
          --hidden-import PyQt5 `
          --hidden-import PyQt5.QtCore `
          --hidden-import PyQt5.QtGui `
          --hidden-import PyQt5.QtWidgets `
          main.py
        
    - name: Rename executable
      run: |
        Move-Item "dist/FileTransfer.exe" "dist/FileTransfer-$env:VERSION.exe" -Force
      shell: pwsh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FileTransfer-${{ env.VERSION }}
        path: dist/FileTransfer-${{ env.VERSION }}.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        name: 文件快传 ${{ env.VERSION }}
        body: |
          ## 文件快传 ${{ env.VERSION }}
          
          ### 下载
          - [Windows 可执行文件](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/FileTransfer-${{ env.VERSION }}.exe)
          
          ### 系统要求
          - Windows 7/8/10/11
          
          ### 更新内容
          请查看 [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)
        files: dist/FileTransfer-${{ env.VERSION }}.exe
        draft: false
        prerelease: false 