name: Build Windows Executable

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag_version:
        description: '版本号 (例如: v1.0.0)'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Create Tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        git tag ${{ github.event.inputs.tag_version }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter==5.2.2 pywin32==305 Pillow==10.2.0
        pip install pyinstaller==6.3.0
        
    - name: Convert JPEG to ICO
      run: |
        python -c "from PIL import Image; img = Image.open('tb.jpeg'); img.save('icon.ico', format='ICO', sizes=[(256, 256)])"
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed `
          --name "FileTransfer" `
          --add-data "tb.jpeg;." `
          --icon "icon.ico" `
          --version-file "version.txt" `
          --hidden-import win32api `
          --hidden-import win32con `
          main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FileTransfer
        path: dist/FileTransfer.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v1
      with:
        name: 文件快传 ${{ github.event.inputs.tag_version || github.ref_name }}
        tag_name: ${{ github.event.inputs.tag_version || github.ref_name }}
        body: |
          ## 文件快传 ${{ github.event.inputs.tag_version || github.ref_name }}
          
          ### 下载
          - [Windows 可执行文件](https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag_version || github.ref_name }}/FileTransfer.exe)
          
          ### 系统要求
          - Windows 7/8/10/11
          
          ### 更新内容
          - 首次发布
          - 支持局域网文件快速传输
          - 支持文件 MD5 校验
          - 支持进度显示和传输速度显示
        files: dist/FileTransfer.exe
        draft: false
        prerelease: false 